### ISSUE TITLE
Option to use SSH instead of password

### ISSUE THREAD

**Issue by michaelplews** [arbox/org-sync#44]
I'm much more comfortable not storing passwords in plaintext. Could we add an option to use ssh instead?

**Comment by michaelplews** [comment]
Thanks for the reply.

From the README:

> Now, let's try to add a new issue. First you have to set a user/password to be able to modify the issue remotely.

> Set the variable org-sync-github-auth to like so: (setq org-sync-github-auth '("ostesting" . "thisisostesting42"))

This means I have to store my username and password in plaintext in my `.emacs` file. Could there be an option to specify the ssh key and use that instead?

**Comment by plajjan** [comment]
@michaelplews ah, right. I agree that it is generally not a good idea to put a plaintext password in your emacs config. However, SSH keys isn't an option because the backends simply don't communicate over SSH (they use HTTP(S)) and so SSH keys aren't a viable authentication method. I will close this because it's nothing org-sync can do anything about.

I would recommend that you look into putting your passwords in .authinfo and encrypting it with GPG :)
